### ISSUE TITLE
The FBPickItem.csv SoItemDateLastPicked field is formatted incorrectly in extract.

### ISSUE THREAD

**Issue by gibblets6** [andvue/fb-etl#2]
FB_SO_PICK_ITEM_READER] finished with status ERROR.
   SoitemDateLastPicked (date) cannot be set to "11-Aug-2014" - doesn't match defined format "yyyy-MM-dd" in record 1, field 3 ("SoitemDateLastPicked"), metadata "FBSOPickItem_csv"; value: '11-Aug-2014'
    Unparseable date: "11-Aug-2014" at position 3

**Comment by lloydclosson** [comment]
This should be resolved in the file with a client id of 7.
